/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ModuleWasteWarriorRouteImport } from './routes/module.waste-warrior'
import { Route as ModuleSaveWaterRouteImport } from './routes/module.save-water'
import { Route as ModuleNatureFriendsRouteImport } from './routes/module.nature-friends'
import { Route as ModuleHealthyMeRouteImport } from './routes/module.healthy-me'

const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleWasteWarriorRoute = ModuleWasteWarriorRouteImport.update({
  id: '/module/waste-warrior',
  path: '/module/waste-warrior',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleSaveWaterRoute = ModuleSaveWaterRouteImport.update({
  id: '/module/save-water',
  path: '/module/save-water',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleNatureFriendsRoute = ModuleNatureFriendsRouteImport.update({
  id: '/module/nature-friends',
  path: '/module/nature-friends',
  getParentRoute: () => rootRouteImport,
} as any)
const ModuleHealthyMeRoute = ModuleHealthyMeRouteImport.update({
  id: '/module/healthy-me',
  path: '/module/healthy-me',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/module/healthy-me': typeof ModuleHealthyMeRoute
  '/module/nature-friends': typeof ModuleNatureFriendsRoute
  '/module/save-water': typeof ModuleSaveWaterRoute
  '/module/waste-warrior': typeof ModuleWasteWarriorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/module/healthy-me': typeof ModuleHealthyMeRoute
  '/module/nature-friends': typeof ModuleNatureFriendsRoute
  '/module/save-water': typeof ModuleSaveWaterRoute
  '/module/waste-warrior': typeof ModuleWasteWarriorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/module/healthy-me': typeof ModuleHealthyMeRoute
  '/module/nature-friends': typeof ModuleNatureFriendsRoute
  '/module/save-water': typeof ModuleSaveWaterRoute
  '/module/waste-warrior': typeof ModuleWasteWarriorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/module/healthy-me'
    | '/module/nature-friends'
    | '/module/save-water'
    | '/module/waste-warrior'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/module/healthy-me'
    | '/module/nature-friends'
    | '/module/save-water'
    | '/module/waste-warrior'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/module/healthy-me'
    | '/module/nature-friends'
    | '/module/save-water'
    | '/module/waste-warrior'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  ModuleHealthyMeRoute: typeof ModuleHealthyMeRoute
  ModuleNatureFriendsRoute: typeof ModuleNatureFriendsRoute
  ModuleSaveWaterRoute: typeof ModuleSaveWaterRoute
  ModuleWasteWarriorRoute: typeof ModuleWasteWarriorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/waste-warrior': {
      id: '/module/waste-warrior'
      path: '/module/waste-warrior'
      fullPath: '/module/waste-warrior'
      preLoaderRoute: typeof ModuleWasteWarriorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/save-water': {
      id: '/module/save-water'
      path: '/module/save-water'
      fullPath: '/module/save-water'
      preLoaderRoute: typeof ModuleSaveWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/nature-friends': {
      id: '/module/nature-friends'
      path: '/module/nature-friends'
      fullPath: '/module/nature-friends'
      preLoaderRoute: typeof ModuleNatureFriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/module/healthy-me': {
      id: '/module/healthy-me'
      path: '/module/healthy-me'
      fullPath: '/module/healthy-me'
      preLoaderRoute: typeof ModuleHealthyMeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  ModuleHealthyMeRoute: ModuleHealthyMeRoute,
  ModuleNatureFriendsRoute: ModuleNatureFriendsRoute,
  ModuleSaveWaterRoute: ModuleSaveWaterRoute,
  ModuleWasteWarriorRoute: ModuleWasteWarriorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
